name: YOUR MOM
on:
 push:
  branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   permissions: 
     contents: read
     packages: write

   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Set up JDK 8
       uses: actions/setup-java@v2
       with:
         distribution: 'adopt'
         java-version: 8
         check-latest: true

     - name: Compute short SHA
       id: sha
       run: echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Build with Gradle
       run: ./gradlew build

     - name: Rename JAR
       run: mv build/libs/*.jar build/libs/LRClient-${{ env.SHORT_SHA }}.jar

     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v3
       with:
         name: LRClient-${{ env.SHORT_SHA }}
         path: build/libs/LRClient-${{ env.SHORT_SHA }}.jar
