name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Setting things
        run: |
          echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "DATE=$(date --date='${{ github.event.head_commit.timestamp }}' -u '+%Y-%m-%dT%H:%M:%S.000Z')" >> $GITHUB_ENV
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew setupCiWorkspace
          ./gradlew build
      - name: Upload artifact
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*liquidbounce-b[0-9|.]*\.jar')
          echo $JAR
<<<<<<< HEAD
          curl --connect-timeout 30 -o /dev/null -F 'payload_json={"content":null,"embeds":[{"color":2302093,"fields":[{"name":"Version","value":"```\n${{ env.VERSION }}\n```","inline":true},{"name":"Branch","value":"```\nmain\n```","inline":true}],"author":{"name":"Newest LRClient","icon_url":"https://tuilazerotwo.xyz/assets/logo.png"},"timestamp":"${{ env.DATE }}"}],"attachments":[]}' -F "file1=@$(echo $JAR)" ${{ secrets.WEBHOOK }}
=======
>>>>>>> f8065083e030ce0080158f46ff45d30f7cb3df25
